### ISSUE TITLE
Changelog / release notes missing.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#14]
When I integrated leader boards / achievements, the gpg-cpp-sdk was at version 1.3
Currently it is at 1.4.1

But there is no changelog, and there are no release notes.

I would like to know what has changed from release to release, especially changes in the API, or usage.

**Comment by stolk** [comment]
gpg-cpp-sdk v2.0 now comes with release notes. 
Thank you!

**Comment by claywilkinson** [comment]
You're welcome! Thank you! for all the feedback!
