### ISSUE TITLE
Deprecated examples: TurnBasedMultiplayerEvent deprecated.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#15]
Is there a cpp multi player example that does not use deprecated API calls?

When building cpp version of ButtonClicker, I get:

> bram@ubuntu64:~/src/cpp-android-basic-samples/samples-android/ButtonClicker$ ndk-build
> [armeabi-v7a] Compile++ thumb: ButtonClickerNativeActivity <= ButtonClickerNativeActivity.cpp
> In file included from jni/ButtonClickerNativeActivity.cpp:28:
> In file included from jni/ButtonClickerNativeActivity.h:28:
> In file included from /home/bram/android-ndk-r10e-64/sources/cxx-stl/llvm-libc++/libcxx/include/sstream:174:
> In file included from /home/bram/android-ndk-r10e-64/sources/cxx-stl/llvm-libc++/libcxx/include/ostream:131:
> In file included from /home/bram/android-ndk-r10e-64/sources/cxx-stl/llvm-libc++/libcxx/include/ios:216:
> In file included from /home/bram/android-ndk-r10e-64/sources/cxx-stl/llvm-libc++/libcxx/include/__locale:21:
> In file included from /home/bram/android-ndk-r10e-64/sources/cxx-stl/llvm-libc++/../../android/support/include/locale.h:39:
> /home/bram/android-ndk-r10e-64/platforms/android-9/arch-arm/usr/include/locale.h:55:1: warning: >empty struct has size 0 in C,
>      size 1 in C++ [-Wextern-c-compat]
> struct lconv { };
> ^
> jni/ButtonClickerNativeActivity.cpp:71:48: warning: 'TurnBasedMultiplayerEvent' is deprecated >[-Wdeprecated-declarations]
>                 gpg::TurnBasedMultiplayerEvent::UPDATED_FROM_APP_LAUNCH) {
>                                               ^
> /home/bram/src/gpg-cpp-sdk/android/include/gpg/types.h:247:26: note: >'TurnBasedMultiplayerEvent' has been explicitly marked
>      deprecated here
> typedef MultiplayerEvent TurnBasedMultiplayerEvent GPG_DEPRECATED;
>                         ^
> 2 warnings generated.

**Comment by claywilkinson** [comment]
Fixed.
