### ISSUE TITLE
ButtonClicker crash: Invalid indirect reference 0x4196dc20 in decodeIndirectRef

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#16]
When starting ButtonClicker, the app crashes with:
 Invalid indirect reference 0x4196dc20 in decodeIndirectRef

I/Adreno-EGL(11001): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL(11001): OpenGL ES Shader Compiler Version: E031.24.00.08+13
I/Adreno-EGL(11001): Build Date: 05/12/14 Mon
I/Adreno-EGL(11001): Local Branch: 0512_AU200_patches
I/Adreno-EGL(11001): Remote Branch: 
I/Adreno-EGL(11001): Local Patches: 
I/Adreno-EGL(11001): Reconstruct Branch: 
D/SSRMv2:TSP:AirViewOnOff(  934): DeviceInfo:: 00000000000
D/SSRMv2:TSP:AirViewOnOff(  934): SettingsAirViewInfo:: 000000000
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
D/PhoneStatusBar( 1218): Status bar WINDOW_STATE_HIDING
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/CustomFrequencyManagerService(  934): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 934  tag : ACTIVITY_RESUME_BOOSTER@6
W/ActivityManager(  934): mDVFSHelper.release()
W/ContextImpl(  934): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1501 com.android.server.InputMethodManagerService$4.run:2827 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack> 
D/CustomFrequencyManagerService(  934): acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 934  pkgName : ACTIVITY_RESUME_BOOSTER@9
I/ServiceKeeper(  934): In getappinfo pid = 934 pkgName = android appinfo = null
I/ServiceKeeper(  934): In getseinfo pid = 934 uid = 1000 seinfo= system
D/ChimeraCfgMgr( 7496): Loading module com.google.android.gms.games from APK com.google.android.play.games
D/ChimeraModuleLdr( 7496): Module APK com.google.android.play.games already loaded
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
V/GamesNativeSDK(11001): Play Games callback indicates connection failure.
I/GamesNativeSDK(11001): UI interaction required to connect to Google Play.
I/com.steenriver.example.games.bc3(11001): Initialized Java UI
W/dalvikvm(11001): Invalid indirect reference 0x4196dc20 in decodeIndirectRef
I/dalvikvm(11001): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm(11001):   | group="main" sCount=0 dsCount=0 obj=0x4174dea0 self=0x416454c8
I/dalvikvm(11001):   | sysTid=11001 nice=0 sched=0/0 cgrp=apps handle=1074237780
I/dalvikvm(11001):   | state=R schedstat=( 102945948 56663276 376 ) utm=3 stm=7 core=1
I/dalvikvm(11001):   at com.sample.helper.NDKHelper.RunOnUiThreadHandler(Native Method)
I/dalvikvm(11001):   at com.sample.helper.NDKHelper$1.run(NDKHelper.java:228)
I/dalvikvm(11001):   at android.os.Handler.handleCallback(Handler.java:733)
I/dalvikvm(11001):   at android.os.Handler.dispatchMessage(Handler.java:95)
I/dalvikvm(11001):   at android.os.Looper.loop(Looper.java:136)
I/dalvikvm(11001):   at android.app.ActivityThread.main(ActivityThread.java:5476)
I/dalvikvm(11001):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(11001):   at java.lang.reflect.Method.invoke(Method.java:515)
I/dalvikvm(11001):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
I/dalvikvm(11001):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
I/dalvikvm(11001):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(11001): 
E/dalvikvm(11001): VM aborting
F/libc    (11001): Fatal signal 6 (SIGABRT) at 0x00002af9 (code=-6), thread 11001 (main)
I/NDKHelper(11001): Activity does not have android:configChanges='orientation|screenSize' attributes in AndroidManifest.xml.
I/com.steenriver.example.games.bc3(11001): Attribute 'MinimumWidth' updating
I/com.steenriver.example.games.bc3(11001): Attribute 'MinimumWidth' updating
I/com.steenriver.example.games.bc3(11001): Attribute 'MinimumWidth' updating
I/com.steenriver.example.games.bc3(11001): Attribute 'MinimumWidth' updating
I/com.steenriver.example.games.bc3(11001): Attribute 'Gravity' updating
I/com.steenriver.example.games.bc3(11001): Attribute 'TextColor' updating
E/cutils  (  338): Failed to mkdirat(/storage/extSdCard/Android): Read-only file system
W/ContextImpl(11001): Failed to ensure directory: /storage/extSdCard/Android/data/com.steenriver.example.games.bc3/files
W/Vold    (  338): Returning OperationFailed - no handler for errno 30
E/cutils  (  338): Failed to mkdirat(/storage/extSdCard/Android): Read-only file system
W/ContextImpl(11001): Failed to ensure directory: /storage/extSdCard/Android/data/com.steenriver.example.games.bc3/files
W/Vold    (  338): Returning OperationFailed - no handler for errno 30
I/com.steenriver.example.games.bc3(11001): Program link log:
I/com.steenriver.example.games.bc3(11001): --From Vertex Shader:
I/com.steenriver.example.games.bc3(11001): --From Fragment Shader:
I/com.steenriver.example.games.bc3(11001): Link was successful.
I/com.steenriver.example.games.bc3(11001): Created Shader 1
I/com.steenriver.example.games.bc3(11001): message 6
I/com.steenriver.example.games.bc3(11001): The window has not been suspended
I/SELinux (  351): Function: selinux_android_load_priority [0], There is no sepolicy file.
I/SELinux (  351):  
I/SELinux (  351): Function: selinux_android_load_priority [1], There is no sepolicy version file.
I/SELinux (  351):  
I/SELinux (  351): Function: selinux_android_load_priority , priority version is VE=SEPF_SM-G900X_4.4.2_0016
I/SELinux (  351):  
I/SELinux (  351):  
I/SELinux (  351): get_selabel_handle: file_contexts is loaded from /file_contexts
I/DEBUG   (  351): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  351): Build fingerprint: 'samsung/kwifixx/kwifi:4.4.2/KOT49H/G900XXXU0ANE5_LLK:user/release-keys'
I/DEBUG   (  351): Revision: '14'
I/DEBUG   (  351): pid: 11001, tid: 11001, name: main  >>> com.steenriver.example.games.bc3 <<<
I/DEBUG   (  351): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
E/LightSensor(  934): RED : 2, GREEN : 2, BLUE : 2, CLEAR : 5, CALCULATED LUX : 0.000000, CCT : 4939.000000, REAL LUX : 0.000000 a_time = 238, gain = 64, ir=1, rp1=1, gp1=1, bp1=1, cp1=4, cpl=3202560
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
I/SurfaceFlinger(  360): id=182 Removed cc3 (8/10)
I/SurfaceFlinger(  360): id=182 Removed cc3 (-2/10)
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
D/CustomFrequencyManagerService(  934): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400  uid : 1000  pid : 934  tag : ACTIVITY_RESUME_BOOSTER@9
E/LightSensor(  934): RED : 2, GREEN : 2, BLUE : 2, CLEAR : 5, CALCULATED LUX : 0.000000, CCT : 4939.000000, REAL LUX : 0.000000 a_time = 238, gain = 64, ir=1, rp1=1, gp1=1, bp1=1, cp1=4, cpl=3202560
D/KeyguardUpdateMonitor( 1218): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1218): handleKeyguardVisibilityChanged(1)
D/PhoneStatusBar( 1218): Status bar WINDOW_STATE_HIDDEN
I/DEBUG   (  351):     r0 00000000  r1 00002af9  r2 00000006  r3 00000000
I/DEBUG   (  351):     r4 00000006  r5 00000016  r6 00002af9  r7 0000010c
I/DEBUG   (  351):     r8 beed0248  r9 a510002d  sl fffff744  fp 00000000
I/DEBUG   (  351):     ip a5400029  sp beecff58  lr 400a41ad  pc 400b3154  cpsr 000f0010
I/DEBUG   (  351):     d0  0000000000000000  d1  0000000000000000
I/DEBUG   (  351):     d2  0000000000000000  d3  0000000000000000
I/DEBUG   (  351):     d4  3ff0000000000000  d5  3fe62e42fefa39ef
I/DEBUG   (  351):     d6  3ff306fe0a31b715  d7  3f90000000000000
I/DEBUG   (  351):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  351):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  351):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  351):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  351):     d16 2065766974614e28  d17 0a29646f6874654d
I/DEBUG   (  351):     d18 002e006900750067  d19 0070007300690044
I/DEBUG   (  351):     d20 004500790061006c  d21 0074006e00650076
I/DEBUG   (  351):     d22 006e006e006f0043  d23 0069007400630065
I/DEBUG   (  351):     d24 3f56c16c16c76a94  d25 3f81a8f2df8150d4
I/DEBUG   (  351):     d26 3fa555555555551c  d27 3fc67e6ae37693f5
I/DEBUG   (  351):     d28 3fe0000000000000  d29 0000000000000001
I/DEBUG   (  351):     d30 fff0000000000000  d31 fffffffeffffffd0
I/DEBUG   (  351):     scr 88000010
I/DEBUG   (  351): 
I/DEBUG   (  351): backtrace:
I/DEBUG   (  351):     #00  pc 00022154  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  351):     #01  pc 000131a9  /system/lib/libc.so (pthread_kill+48)
I/DEBUG   (  351):     #02  pc 000133bd  /system/lib/libc.so (raise+10)
I/DEBUG   (  351):     #03  pc 000120f3  /system/lib/libc.so
I/DEBUG   (  351):     #04  pc 00021a08  /system/lib/libc.so (abort+4)
I/DEBUG   (  351):     #05  pc 0004963f  /system/lib/libdvm.so (dvmAbort+78)
I/DEBUG   (  351):     #06  pc 0004dfa7  /system/lib/libdvm.so (dvmDecodeIndirectRef(Thread*, _jobject*)+146)
I/DEBUG   (  351):     #07  pc 00050d5f  /system/lib/libdvm.so
I/DEBUG   (  351):     #08  pc 000773e1  /data/app-lib/com.steenriver.example.games.bc3-2/libButtonClickerNativeActivity.so (jui_helper::JUIToast::InitToast()+224)
I/DEBUG   (  351):     #09  pc 000774b3  /data/app-lib/com.steenriver.example.games.bc3-2/libButtonClickerNativeActivity.so (jui_helper::JUIToast::JUIToast(char const*)+58)
I/DEBUG   (  351):     #10  pc 000705eb  /data/app-lib/com.steenriver.example.games.bc3-2/libButtonClickerNativeActivity.so
I/DEBUG   (  351):     #11  pc 000fc727  /data/app-lib/com.steenriver.example.games.bc3-2/libButtonClickerNativeActivity.so (Java_com_sample_helper_NDKHelper_RunOnUiThreadHandler+10)
I/DEBUG   (  351):     #12  pc 00020e4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
I/DEBUG   (  351):     #13  pc 00051aef  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
I/DEBUG   (  351):     #14  pc 000534d1  /system/lib/libdvm.so (dvmResolveNativeMethod(unsigned int const*, JValue*, Method const*, Thread*)+184)
I/DEBUG   (  351):     #15  pc 0002a2e0  /system/lib/libdvm.so
I/DEBUG   (  351):     #16  pc 00031790  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/DEBUG   (  351):     #17  pc 0002ee28  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/DEBUG   (  351):     #18  pc 00064239  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
I/DEBUG   (  351):     #19  pc 0006c50f  /system/lib/libdvm.so
I/DEBUG   (  351):     #20  pc 0002a2e0  /system/lib/libdvm.so
I/DEBUG   (  351):     #21  pc 00031790  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
I/DEBUG   (  351):     #22  pc 0002ee28  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
I/DEBUG   (  351):     #23  pc 00063f55  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
I/DEBUG   (  351):     #24  pc 0004d6d7  /system/lib/libdvm.so
I/DEBUG   (  351):     #25  pc 000529af  /system/lib/libandroid_runtime.so
I/DEBUG   (  351):     #26  pc 00053f43  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+354)
I/DEBUG   (  351):     #27  pc 0000105b  /system/bin/app_process
I/DEBUG   (  351):     #28  pc 0000e513  /system/lib/libc.so (__libc_init+50)
I/DEBUG   (  351):     #29  pc 00000d7c  /system/bin/app_process
I/DEBUG   (  351): 
I/DEBUG   (  351): stack:
I/DEBUG   (  351):          beecff18  dead4321  
I/DEBUG   (  351):          beecff1c  00000000  
I/DEBUG   (  351):          beecff20  a5400029  
I/DEBUG   (  351):          beecff24  beed0248  [stack]
I/DEBUG   (  351):          beecff28  a510002d  
I/DEBUG   (  351):          beecff2c  fffff744  
I/DEBUG   (  351):          beecff30  00000000  
I/DEBUG   (  351):          beecff34  400b75d1  /system/lib/libc.so (snprintf+80)
I/DEBUG   (  351):          beecff38  33313833  
I/DEBUG   (  351):          beecff3c  20302036  
I/DEBUG   (  351):          beecff40  beecffb4  [stack]
I/DEBUG   (  351):          beecff44  00000000  
I/DEBUG   (  351):          beecff48  00000000  
I/DEBUG   (  351):          beecff4c  30203020  
I/DEBUG   (  351):          beecff50  00004000  
I/DEBUG   (  351):          beecff54  beecffc2  [stack]
I/DEBUG   (  351):     #00  beecff58  00000006  
I/DEBUG   (  351):          beecff5c  00000016  
I/DEBUG   (  351):          beecff60  00002af9  
I/DEBUG   (  351):          beecff64  a5400029  
I/DEBUG   (  351):          beecff68  a5400029  
I/DEBUG   (  351):          beecff6c  400a41ad  /system/lib/libc.so (pthread_kill+52)
I/DEBUG   (  351):     #01  beecff70  00000006  
I/DEBUG   (  351):          beecff74  00000000  
I/DEBUG   (  351):          beecff78  00000000  
I/DEBUG   (  351):          beecff7c  400a43c1  /system/lib/libc.so (raise+14)
I/DEBUG   (  351):     #02  beecff80  beecff8c  [stack]
I/DEBUG   (  351):          beecff84  400a30f7  /system/lib/libc.so
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near r1:
I/DEBUG   (  351):     00002ad8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002ae8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002af8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b08 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b18 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b28 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b38 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b48 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b58 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b68 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b78 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b88 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b98 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002ba8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002bb8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002bc8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near r6:
I/DEBUG   (  351):     00002ad8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002ae8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002af8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b08 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b18 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b28 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b38 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b48 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b58 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b68 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b78 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b88 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002b98 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002ba8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002bb8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     00002bc8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near r8:
I/DEBUG   (  351):     beed0228 6d5f1df4 416454d8 beed0294 77f074b7  
I/DEBUG   (  351):     beed0238 beed0248 fffff744 00000000 77f005ef  
I/DEBUG   (  351):     beed0248 7804d57c 00000000 00000000 00000000  
I/DEBUG   (  351):     beed0258 00000000 3f800000 00000000 0645d484  
I/DEBUG   (  351):     beed0268 7273c490 416454c8 beed0294 77f8c729  
I/DEBUG   (  351):     beed0278 6d9eb570 41667e50 6d5f1df0 00000001  
I/DEBUG   (  351):     beed0288 00000000 42918468 428b9a84 41698af3  
I/DEBUG   (  351):     beed0298 6d5f1df0 77d9a3c2 77f8c71d 416454d8  
I/DEBUG   (  351):     beed02a8 7912703d 78f3df30 00000000 00000000  
I/DEBUG   (  351):     beed02b8 78f3def0 400df394 77f8c71d 400a241f  
I/DEBUG   (  351):     beed02c8 400db000 79127008 00000000 78f3def0  
I/DEBUG   (  351):     beed02d8 00000000 4009ed35 72771128 4169a717  
I/DEBUG   (  351):     beed02e8 00000000 00000018 00000018 428ae008  
I/DEBUG   (  351):     beed02f8 00000018 41667fc0 00000022 41713ea0  
I/DEBUG   (  351):     beed0308 428b9a84 4298a270 41641b48 41641b48  
I/DEBUG   (  351):     beed0318 4298a270 416be487 00000002 6fa251a5  
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near r9:
I/DEBUG   (  351):     a510000c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510001c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510002c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510003c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510004c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510005c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510006c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510007c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510008c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a510009c ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000ac ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000bc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000cc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000dc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000ec ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a51000fc ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near ip:
I/DEBUG   (  351):     a5400008 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400018 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400028 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400038 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400048 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400058 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400068 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400078 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400088 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a5400098 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000a8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000b8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000c8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000d8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000e8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351):     a54000f8 ffffffff ffffffff ffffffff ffffffff  
I/DEBUG   (  351): 
I/DEBUG   (  351): memory near sp:
I/DEBUG   (  351):     beecff38 33313833 20302036 beecffb4 00000000  
I/DEBUG   (  351):     beecff48 00000000 30203020 00004000 beecffc2  
I/DEBUG   (  351):     beecff58 00000006 00000016 00002af9 a5400029  
I/DEBUG   (  351):     beecff68 a5400029 400a41ad 00000006 00000000  
I/DEBUG   (  351):     beecff78 00000000 400a43c1 beecff8c 400a30f7  
I/DEBUG   (  351):     beecff88 00000000 ffffffdf 400db2c4 400db22c  
I/DEBUG   (  351):     beecff98 00000000 400a5cb7 41713ea0 41713ea0  
I/DEBUG   (  351):     beecffa8 dead4321 400b2a0c 00000000 41690643  
I/DEBUG   (  351):     beecffb8 beed0040 6c756e28 0000296c 00000000  
I/DEBUG   (  351):     beecffc8 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beecffd8 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beecffe8 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beecfff8 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beed0008 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beed0018 00000000 00000000 00000000 00000000  
I/DEBUG   (  351):     beed0028 00000000 00000000 00000000 00000000  
I/DEBUG   (  351): 
I/DEBUG   (  351): code around pc:
I/DEBUG   (  351):     400b3134 e8bd00f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  351):     400b3144 ea006e48 e92d50f0 e3a07f43 ef000000  
I/DEBUG   (  351):     400b3154 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  351):     400b3164 ea006e40 e92d50f0 e3a070ee ef000000  
I/DEBUG   (  351):     400b3174 e8bd50f0 e3700a01 912fff1e e2600000  
I/DEBUG   (  351):     400b3184 ea006e38 f200429a bf0080b9 f040f891  
I/DEBUG   (  351):     400b3194 4001e92d f2c02a04 2a1080a5 8093f2c0  
I/DEBUG   (  351):     400b31a4 f2c02a20 2a408088 ea4fdb7f f1bc1c92  
I/DEBUG   (  351):     400b31b4 dd6c0f0a 0600e92d 0f40f1bc f500dd4a  
I/DEBUG   (  351):     400b31c4 f5016e80 ebae7920 ea4f0e09 ea4f5e4e  
I/DEBUG   (  351):     400b31d4 f50e5e5e ebbc7e20 dd3b1f9e f04fbfc4  
I/DEBUG   (  351):     400b31e4 ebd9090a dd35199e 0a0eeb01 0a3ff02a  
I/DEBUG   (  351):     400b31f4 1c9eebac bfd245e1 0c09ebac f04f46e1  
I/DEBUG   (  351):     400b3204 f8910c00 f891f240 f921f280 f921028d  
I/DEBUG   (  351):     400b3214 f8da428d f1b93000 f9000901 f900028d  
I/DEBUG   (  351):     400b3224 f10a428d d1ee0a40 0f00f1bc f5bcd02b  
I/DEBUG   (  351): 
I/DEBUG   (  351): code around lr:
I/DEBUG   (  351):     400a418c 447b4b13 42b3e010 6a1ed10e 44784811  
I/DEBUG   (  351):     400a419c ec84f7fb ea0cf00d 46224631 efcef00e  
I/DEBUG   (  351):     400a41ac d00a3001 e00b2400 2b00681b 480ad1eb  
I/DEBUG   (  351):     400a41bc 44782403 ec72f7fb f001e002 6804fa23  
I/DEBUG   (  351):     400a41cc fa20f001 46206005 bf00bd70 0003b226  
I/DEBUG   (  351):     400a41dc 0003b21a 0003b212 0003b1ee bf7ef7ff  
I/DEBUG   (  351):     400a41ec 4a3e4b3d e92d447b b08b43f0 4606589c  
I/DEBUG   (  351):     400a41fc 6823460d 930946a1 fa04f001 8000f8d0  
I/DEBUG   (  351):     400a420c d0482d00 f0104628 280ff91b d8444604  
I/DEBUG   (  351):     400a421c ffe4f7ff d1064286 4629200f e8d6f00d  
I/DEBUG   (  351):     400a422c d03c2800 482ee02e f7fb4478 482debb6  
I/DEBUG   (  351):     400a423c e0154478 d11342b0 482b6a06 f7fb4478  
I/DEBUG   (  351):     400a424c 4a2aec2e 46332120 a801447a f992f013  
I/DEBUG   (  351):     400a425c a8012101 fcb0f01a 46061c42 e011d104  
I/DEBUG   (  351):     400a426c 28006800 e02cd1e6 46294630 f00d4622  
I/DEBUG   (  351):     400a427c 1c43e912 d11e4607 f9c4f001 29046801

**Comment by ggfan** [comment]
yes, thank you for the findings!  I am working on a fix for it since now we are close to get 64 bit gpg out.  This branch was too old so I will fork a new one and start up the fixing process.  after I merge it in, I will drop a note here and then retire this branch.

**Comment by ggfan** [comment]
this one seems already fixed.  Now if you are using latest gpg C++ SDK version  2.0,  android-support-v4.jar ( from android sdk  ) need to be linked to those projects; otherwise game could not log in
