### ISSUE TITLE
ButtonClicker: Class not found when unmarshalling

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#17]
When I build and run the c++ ButtonClicker example, and create a room, I get this in the device log.
(Note: the room creation does seem to succeed, and I can see the room, and launch the match.)

device:  Samsung Galaxy Note 4.
model nr: SM-N910F
android: 4.4.4
device log:

I/libjingle( 6512): virtual int games_rtmp::BuzzSubscriptionsTask::SetOnDisconnectTask::ProcessStart(): Send-on-disconnect: <cli:message to="games@ob.talk.google.com" type="headline" xmlns:cli="jabber:client"><push xmlns="google:push" channel="games.google.com/buzzbot" sendOnDisconnect="true"><recipient to="play-presence@games.bot.talk.google.com">Q2hvS0NRanotNGptaVJrUUFoQUJHQUFnX19fX19fX19fX19fQVJEQ3h1R25zY0c1ekNZOmdhbWVzQG9iLnRhbGsuZ29vZ2xlLmNvbS9nYW1lc19hbmRyOTVDNUFFOTk=</recipient></push></cli:message>
I/com.steenriver.example.games.bc3(25980): created a room 1
E/Parcel  (  935): Class not found when unmarshalling: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  935): java.lang.ClassNotFoundException: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  935): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  935): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  935): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  935): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  935): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  935): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  935): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  935): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  935): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  935): 	at android.content.Intent.getStringExtra(Intent.java:5285)
E/Parcel  (  935): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1586)
E/Parcel  (  935): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1167)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4507)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4389)
E/Parcel  (  935): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:161)
E/Parcel  (  935): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3013)
E/Parcel  (  935): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  935): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  935): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/games/multiplayer/realtime/RoomEntity
E/Parcel  (  935): 	... 18 more
E/Parcel  (  935): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.multiplayer.realtime.RoomEntity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  935): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  935): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  935): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  935): 	... 18 more
V/ApplicationPolicy(  935): isApplicationStateBlocked userId 0 pkgname com.google.android.play.games

**Comment by stolk** [comment]
This is still present in GPG v2.0

```
E/Parcel  (  951): Class not found when unmarshalling: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  951): java.lang.ClassNotFoundException: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  951): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  951): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  951): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  951): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  951): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  951): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  951): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  951): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  951): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  951): 	at android.content.Intent.getStringExtra(Intent.java:5128)
E/Parcel  (  951): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1466)
E/Parcel  (  951): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1054)
E/Parcel  (  951): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4068)
E/Parcel  (  951): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3962)
E/Parcel  (  951): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159)
E/Parcel  (  951): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2636)
E/Parcel  (  951): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  951): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  951): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/games/multiplayer/realtime/RoomEntity
E/Parcel  (  951): 	... 18 more
E/Parcel  (  951): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.multiplayer.realtime.RoomEntity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  951): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
E/Parcel  (  951): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  951): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  951): 	... 18 more
```

**Comment by stolk** [comment]
Could it be possible that it is a SAMSUNG bug?
I test on Samsung devices.

Is the unmarshalled file from google play, or from android?

http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=272802

**Comment by claywilkinson** [comment]
Can you share:
what version of play services you are running on the device? 
What version of the client lib are you including when building?
What version of the Play Games app running on the device?

**Comment by stolk** [comment]
Play Games version 3.2.21
GPG v2.0
Google Play Services rev 26

**Comment by claywilkinson** [comment]
Thanks - I'll pass it along and let you know what they find out.

**Comment by stolk** [comment]
Any update on this? I still get these:
```
E/Parcel  (  965): Class not found when unmarshalling: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  965): java.lang.ClassNotFoundException: com.google.android.gms.games.multiplayer.realtime.RoomEntity
E/Parcel  (  965): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  965): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  965): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  965): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  965): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  965): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  965): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  965): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  965): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  965): 	at android.content.Intent.getStringExtra(Intent.java:5285)
E/Parcel  (  965): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1586)
E/Parcel  (  965): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1167)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4507)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4389)
E/Parcel  (  965): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:161)
E/Parcel  (  965): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3013)
E/Parcel  (  965): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  965): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  965): Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/games/multiplayer/realtime/RoomEntity
E/Parcel  (  965): 	... 18 more
E/Parcel  (  965): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.games.multiplayer.realtime.RoomEntity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  965): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  965): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  965): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  965): 	... 18 more
```

**Comment by claywilkinson** [comment]
This is the a scary looking exception that actually has no impact on the functionality.  Apparently Samsung inspects  intents which can trigger the message.
