### ISSUE TITLE
google-play-services_lib rev29 causes resource not found.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#26]
After upgrading my google-play-services_lib to the latest (rev29), I now get this error when building:

```
[aapt] /home/bram/apps/Buggy/Android/google-play-services_lib/res/values-v21/appinvite_styles.xml:5:
error: Error retrieving parent for item: No resource found that matches the given name 
 '@android:style/Theme.Material.Light.DialogWhenLarge.NoActionBar'.
```

I tried setting AndroidManifest.xml's android:targetSdkVersion to 21, to no avail.

I tried setting project.properties target=android-21, to no avail.

Moving to older version of google-play-services_lib fixes this issue.

**Comment by claywilkinson** [comment]
I believe this was a bad version of 21, using <21 > 21 should work fine.  Alternatively, you can copy the style out of a project using the more recent tools and copy it into your project.
