### ISSUE TITLE
Where should ./gpg-cpp-sdk directory be located?

### ISSUE THREAD

**Issue by S3riousSam** [playgameservices/cpp-android-basic-samples#28]
The How-to run a sample says that the developper must download the _Google Play Game Services C++ SDK_ and unzip it to the ./gpg-cpp-sdk directory.

I'm sorry that I cannot figure out where that folder should go...

Thanks for clarifying this instruction for me.

**Comment by claywilkinson** [comment]
The instructions for a command line build are in [README.build](https://github.com/playgameservices/cpp-android-basic-samples/blob/master/samples-android/README.build#L35) - it says that NDK_MODULE_PATH should be set to the location that the SDK was expanded.  I suggest in Common/gpg-sdk.

You can also try to use the experimental Android Studio support to build with Gradle: http://tools.android.com/tech-docs/android-ndk-preview

**Comment by S3riousSam** [comment]
"NDK_MODULE_PATH to the location of the Play Games cpp libraries."... I understand this refers to the root of the cpp-android-basic-samples zip content, right?

**Comment by claywilkinson** [comment]
NDK_MODULE_PATH should be the directory that the C++ SDK was unzipped into.

**Comment by S3riousSam** [comment]
In build_sample.sh, "${ANDROID_HOME}/tools/android"... "android" refers to android.bat of the SDK\tools folder, right? (the build.sh scripts complains that I have ANDROID_HOME wrong (ERROR: F:\Android\ADT\SDK\tools\android does not exist), but android.bat exists there...

**Comment by claywilkinson** [comment]
Might be a windows vs. non-windows issue.  can you try copying android.bat to android and see if still works?  I'll look into later today for a more permanent solution.

**Comment by S3riousSam** [comment]
Likely Windows... so I guess it was not tested on Windows? 

I had to make these changes to make the script building (however, it looks like it still does not produce any lib nor apk yet):

# Paths to check
declare -r required_paths=( \
  "${ANDROID_HOME}/tools" \

declare -r android_tool="${ANDROID_HOME}/tools/android.bat"

Building...
/bin/sh: mount : command not found
/bin/sh: tr : command not found
/bin/sh: awk : command not found

**Comment by claywilkinson** [comment]
Ugh - it does look the script is not windows friendly.   I'll take a look as soon as I can.

**Comment by S3riousSam** [comment]
Thanks!

Check your linked in account to reach me for faster investigation (I have a thread opened in stackoverflow also).

**Comment by claywilkinson** [comment]
Did you get this working?

**Comment by S3riousSam** [comment]
Using Android Studio, yes. That was not an issue building it (after MANY guesses & try), but the sample application was crashing with UnsatisfiedLinkError exception (library not found)... which led me to try all kind of workarounds. At last I had to modify ButtonClickerNativeActivity.java to make it work...

**Comment by gguuss** [comment]
Build all samples on Windows using Gradle
-----------------------------------------
1. Unzip the Play Games Services to the sample folder. The `gpg-cpp-sdk` folder should be in the same folder containing the `samples-android` folder.
2. Install Android Studio
3. Set the path to the Android SDK

    set ANDROID_HOME=C:\Users\<yourusername>\AppData\Local\Android\sdk

4. Add the SDK to your path

    set PATH=%PATH%;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools

5. Set the path to the Android NDK

    set ANDROID_NDK_HOME=C:\Users\<yourusername>\Desktop\android-ndk-r10e

6. (Optional) On some versions of Windows it is helpful to map the samples folder to a shortened path.

    subst C:\<full-path-to-sample-folder> G:

7. Execute the build script

    G:
    gradlew.bat sync
    gradlew.bat assemble
