### ISSUE TITLE
.cproject file is missing for minimalist example

### ISSUE THREAD

**Issue by mthiesen** [playgameservices/cpp-android-basic-samples#3]
There is no .cproject file in the minimalist folder, therefore the native library is not build when the project is imported into ADT.

**Comment by ggfan** [comment]
Oops, sorry about the problem. with  the latest android studio port, this should be handled. Eclipse IDE build is replaced with android studio ( disable the "instant run" if android studio preview 2.0 is used ); if you need ndk-build, just go to Minimalist/src/main, run build.sh. it should work
