### ISSUE TITLE
gpg playgame downloading in gradle is not efficient

### ISSUE THREAD

**Issue by ggfan** [playgameservices/cpp-android-basic-samples#37]
every time when I do clean from android studio, I gpg_cpp_sdk.zip is removed from my disk; when I build again, it get downloaded again:
  -rw-r--r--  1 gfan  eng  50072904 Apr 18 15:25 gpg_cpp_sdk.zip
so every time I click a "rebuild", I am re-downloading this 50MB file for nothing.

need add if (file_not_existing) do this download thing logical into gradle.

**Comment by claywilkinson** [comment]
Thanks for the feedback!  The check for an existing file has been added.
