### ISSUE TITLE
x86_64 ABI missing.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#43]
Play Games C++ SDK Version 2.1 is missing an ABI.

Present are:
x86, armeabi-v7a, armeabi, arm64-v8a

Missing is:
x86_64

Downloaded from:
https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v2.1.zip

**Comment by stolk** [comment]
Hello?
Has 'Google Play Games C++ SDK' been abandoned?

**Comment by claywilkinson** [comment]
64 bit is currently not supported, but I've passed along the request to the SDK team.
