### ISSUE TITLE
Detected incorrect implementation

### ISSUE THREAD

**Issue by mkdotcom** [playgameservices/cpp-android-basic-samples#45]
Hello

I use GPG C++ in my game.
The android dev console give me this warning for my game:

> Detected incorrect implementation
> Your game has incorrectly implemented the following Play Games services: Achievements.

But all achievements works fine in the game...
Is it because google automatic check only try to find java API achievements called, or something like that? Or is there really an "issue" in my code and somebody knows what I can do?

thanks

**Comment by claywilkinson** [comment]
The checklist specific to achievements is here: https://developers.google.com/games/services/checklist#2_achievements
If this is an early version uploaded, maybe not all achievements are unlocked? (or that you have less than 5?)

**Comment by mkdotcom** [comment]
there is more than 5 achievements and the checklist seems ok
some achievements are very difficult to get (earning all stars on all levels for example), could it be the reason why there is this "detected incorrect implementation"?
is there no way to know precisely why the dev console raises this warning?

**Comment by mkdotcom** [comment]
fyi the game is this one : https://play.google.com/store/apps/details?id=net.mkdc.cr

**Comment by claywilkinson** [comment]
If you think the analysis is incorrect, emailing the support team from the play console (under the help menu) with your situation.  I guess you could upload a version of the apk that moves the super-difficult achievement unlocking to some place more easy to achieve.  This would confirm your suspicion.

**Comment by mkdotcom** [comment]
support team just sent me back to the usual help page which doesn't help at all
