### ISSUE TITLE
CRASH: com.google.android.gms.games.NativeSdkCallbacks

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#47]
I have a working and published game that I recently migrated from Ant to AndroidStudio.
After conversion, the game crashes on launch:

```

06-17 19:48:18.187 30372-30417/com.steenriver.buggy E/GamesNativeSDK: Exception in dalvik/system/DexClassLoader.loadClass: java.lang.IncompatibleClassChangeError: Class com.google.android.gms.games.NativeSdkCallbacks implements non-interface class com.google.android.gms.nearby.connection.Connections$ConnectionRequestListener (declaration of 'com.google.android.gms.games.NativeSdkCallbacks' appears in /data/user/0/com.steenriver.buggy/app_.gpg.classloader/d75c8e1bbeab9e1ddffb9d332585db71.jar).
06-17 19:48:18.207 30372-30417/com.steenriver.buggy A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: RegisterNatives received NULL jclass
06-17 19:48:18.207 30372-30417/com.steenriver.buggy A/art: art/runtime/java_vm_ext.cc:410]     in call to RegisterNatives
```

My device is running latest Google Play Games 3.9.08

In my Gradle file, I have these dependencies:
```
    compile 'com.android.support:support-v4:26.0.+'

    compile 'com.android.support:appcompat-v7:26.0.+'

    compile 'com.google.android.gms:play-services:11.0.1'
```

This is from a previously working code base, that didn't use Gradle, but used google-play-services_lib from sep 2015.

**Comment by stolk** [comment]
Some more information:

If I downgrade to play services 10.0.1 it does not crash.
So in gradle file:
`    compile 'com.google.android.gms:play-services:10.0.1'`

Then, it works:
```
06-17 20:38:16.967 1542-1606/com.steenriver.buggy I/GamesNativeSDK: Connecting to Google Play...
06-17 20:38:16.967 1542-1542/com.steenriver.buggy I/HwCust: Constructor found for class android.widget.HwCustTextViewImpl
06-17 20:38:16.967 1542-1542/com.steenriver.buggy D/HwCust: Create obj success use class android.widget.HwCustTextViewImpl
06-17 20:38:16.977 1542-1542/com.steenriver.buggy V/GamesNativeSDK: Received Activity Resume Event.
```

It is only 11.0.1 that crashes.

**Comment by claywilkinson** [comment]
The error you are referencing is caused by an interface being changed to an abstract class in 10.2.0.  The best course of action in my opinion is to update to the latest plugin version and the latest play-services version.

**Comment by qbit86** [comment]
> The error you are referencing is caused by an interface being changed to an abstract class in 10.2.0.

In which jar/aar this `com.google.android.gms.games.NativeSdkCallbacks` is implemented? What exactly should we update to get rid of this bug?
I have updated plugin and dependencies, but issue is still here.

**Comment by naveedabdullah** [comment]
Upgrade play-services-games to play-services-gamesv17.0.0 to fix it
