### ISSUE TITLE
Old play games services are used by cpp example code.

### ISSUE THREAD

**Issue by stolk** [playgameservices/cpp-android-basic-samples#49]
The cpp examples use old version of the java and cpp libraries.

In cpp-android-basic-samples/samples-android/Common/gpg-sdk/build.gradle this file is downloaded:
```
https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v2.1.zip
```
Whereas gpg-cpp-sdk.v2.3.zip is now available.

Similarly, the examples are built against com.google.android.gms:play-services-games:10.0.0 whereas version 11.0.0 is now available.

**Comment by stolk** [comment]
Also, what is the reason that GPG is limited to NDK r10e which is more than 2 yrs old?
We're at NDK r15b now.

**Comment by claywilkinson** [comment]
C++ SDK 3.0 requires r14 or greater.
