### ISSUE TITLE
Does this mean google play services will not work with ndk r10 or above?

### ISSUE THREAD

**Issue by Ams0x57** [playgameservices/cpp-android-basic-samples#52]
Android studio which is maintained by Google can integrate the latest version of ndk. Luckily the game engine I was interested in managed to integrate itself to both android studio and ndk, their latest version. Now google play services which is also maintained by Google cannot keep their c++ SDK up to date with android ndk?
Please explain to me what am I missing here! appreciate it.

P.S. Tried to build the sample game in android studio, not only the .mk file in core bundle fires errors, but the .mk files in the sample game itself were pointing to non-existing directories namely "gpg-cpp-sdk". I however copied the necessary files into the game folder and it worked. But still the makefile inside the ndk bundle error was persistent (it has to have something to do with the ndk r10 or earlier thing..)

**Comment by claywilkinson** [comment]
The current release, 3.0 of the C++ SDK requires r14 or above.  The samples have been updated to use CMake, which is the preferred method for native development using Android Studio.
