### ISSUE TITLE
Duplicate md5_block_data_order symbol

### ISSUE THREAD

**Issue by dakikifr** [playgameservices/cpp-android-basic-samples#7]
Hi,

I can't link with the new version of the sdk (cpp v1.4) on android, I'm having duplicate symbols during link phase:
ld: error: libcurl.a(md5_dgst.o): multiple definition of 'md5_block_data_order'
gpg-cpp-sdk/android/lib/gnustl/armeabi/libgpg.a: previous definition here

With sdk 1.3, it was linking just fine on both iOS and Android
With sdk 1.4, it links fine on iOS, but I've that error on Android

I'm using a prebuilt version of libcurl on my project. I tried to remove the md5_dgst.o file from my libcurl file without success.

Any advice?

**Comment by dakikifr** [comment]
Hi,

what can I do to solve this issue?
I had to roll back to sdk 1.3, but I won't be able to keep using this version for long, I'll need the features of newest sdk some day.

**Comment by claywilkinson** [comment]
Thanks for your patience! There should be an updated SDK soon.

**Comment by dakikifr** [comment]
Sure no problem, I just wanted to know if you think of that as an issue from the sdk itself or not :)
While I'm there, I'll create a new issue I encountered.

**Comment by BaderThanBad** [comment]
Im having the same issue, has the SDK been updated?

**Comment by claywilkinson** [comment]
@BaderThanBad -  it has not been updated yet, but will be very soon!

**Comment by claywilkinson** [comment]
version 1.4.1 of the SDK is now available.
