### ISSUE TITLE
Achievements in iOS not properly showing XP

### ISSUE THREAD

**Issue by dakikifr** [playgameservices/cpp-android-basic-samples#8]
Hi,

Using sdk 1.3 or 1.4, if I open the achievements UI (the default one), I'm not seeing the XP associated with the achievements (I have a "0 XP" string instead).
The same code on android works fine and I see the correct XP value.

Got the same "bug" from the toasts on iOS (if it helps).
Thanks

**Comment by dakikifr** [comment]
I forgot to mention this is from an alpha version of the game (PlayGames store listing is still in draft mode).
But well, since it works fine on android, maybe it's not related to being unpublished.

**Comment by samtstern** [comment]
@dakikifr since this is an iOS bug, could you re-open the issue on cpp-ios-basic-samples?  Also could you post a screenshot of what you are seeing on Android and what you are seeing on iOS so I can better understand the issue?

**Comment by dakikifr** [comment]
Hi, I did, but never get any answer.

**Comment by tyrmullen** [comment]
I believe this issue is now resolved; until published, the HTTP responses from the server will return "0 XP".  After publishing, this issue should go away.

**Comment by dakikifr** [comment]
You are right that this one can be solved since the issue is iOS only.
